/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalstp;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class EditPatient extends javax.swing.JFrame implements submit{

    /**
     * Creates new form EditPatient
     */
    
     String fileLoc = "C:\\Users\\nicol\\Desktop\\Database\\Patient";
     String fileLocDoctor = "C:\\Users\\nicol\\Desktop\\Database\\Doctor\\";
     String ageM;
     boolean a = true;
    public EditPatient() {
        initComponents();
        allDoc();
        jButton2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        patientName = new javax.swing.JLabel();
        pName = new javax.swing.JTextField();
        pAllergies = new javax.swing.JTextField();
        pAge = new javax.swing.JTextField();
        pillness = new javax.swing.JTextField();
        pWeight = new javax.swing.JTextField();
        pAddress = new javax.swing.JTextField();
        pHeight = new javax.swing.JTextField();
        pContact = new javax.swing.JTextField();
        rAddress = new javax.swing.JTextField();
        pEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        rName = new javax.swing.JTextField();
        rContact = new javax.swing.JTextField();
        relation = new javax.swing.JTextField();
        rEmail = new javax.swing.JTextField();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        day = new javax.swing.JComboBox<>();
        pSex = new javax.swing.JComboBox<>();
        pBloodType = new javax.swing.JComboBox<>();
        pCivilStatus = new javax.swing.JComboBox<>();
        doc = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        checkbox1 = new java.awt.Checkbox();
        Schedule = new javax.swing.JLabel();
        assistant = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        depart = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1092, 702));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientName.setForeground(new java.awt.Color(0, 0, 0));
        patientName.setText("Patient Name ");
        jPanel1.add(patientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 140, 70));

        pName.setBackground(new java.awt.Color(165, 165, 165));
        pName.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        pName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNameActionPerformed(evt);
            }
        });
        jPanel1.add(pName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 420, 20));

        pAllergies.setBackground(new java.awt.Color(165, 165, 165));
        pAllergies.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jPanel1.add(pAllergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 250, 40));

        pAge.setBackground(new java.awt.Color(165, 165, 165));
        pAge.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        pAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAgeActionPerformed(evt);
            }
        });
        jPanel1.add(pAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 50, 20));

        pillness.setBackground(new java.awt.Color(165, 165, 165));
        pillness.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jPanel1.add(pillness, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 340, -1));

        pWeight.setBackground(new java.awt.Color(165, 165, 165));
        pWeight.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jPanel1.add(pWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 50, -1));

        pAddress.setBackground(new java.awt.Color(165, 165, 165));
        pAddress.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jPanel1.add(pAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 350, -1));

        pHeight.setBackground(new java.awt.Color(165, 165, 165));
        pHeight.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jPanel1.add(pHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 50, -1));

        pContact.setBackground(new java.awt.Color(165, 165, 165));
        pContact.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        pContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pContactActionPerformed(evt);
            }
        });
        jPanel1.add(pContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 150, -1));

        rAddress.setBackground(new java.awt.Color(165, 165, 165));
        rAddress.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jPanel1.add(rAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 400, 20));

        pEmail.setBackground(new java.awt.Color(165, 165, 165));
        pEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jPanel1.add(pEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 310, -1));

        jButton1.setBackground(new java.awt.Color(68, 114, 196));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Show Previous Patient Information");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 255), null, null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 250, 20));

        rName.setBackground(new java.awt.Color(165, 165, 165));
        rName.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        rName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNameActionPerformed(evt);
            }
        });
        jPanel1.add(rName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 460, -1));

        rContact.setBackground(new java.awt.Color(165, 165, 165));
        rContact.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jPanel1.add(rContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 180, -1));

        relation.setBackground(new java.awt.Color(165, 165, 165));
        relation.setText(" ");
        relation.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jPanel1.add(relation, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 150, 20));

        rEmail.setBackground(new java.awt.Color(165, 165, 165));
        rEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jPanel1.add(rEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 270, 20));

        month.setBackground(new java.awt.Color(165, 165, 165));
        month.setEditable(true);
        month.setForeground(new java.awt.Color(0, 0, 0));
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        month.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        jPanel1.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 80, 20));

        year.setBackground(new java.awt.Color(165, 165, 165));
        year.setEditable(true);
        year.setForeground(new java.awt.Color(0, 0, 0));
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901", "1900" }));
        year.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 60, 20));

        day.setBackground(new java.awt.Color(165, 165, 165));
        day.setEditable(true);
        day.setForeground(new java.awt.Color(0, 0, 0));
        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });
        jPanel1.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 60, 20));

        pSex.setBackground(new java.awt.Color(165, 165, 165));
        pSex.setForeground(new java.awt.Color(0, 0, 0));
        pSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "Female", "Male" }));
        pSex.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        pSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pSexActionPerformed(evt);
            }
        });
        jPanel1.add(pSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 90, 20));

        pBloodType.setBackground(new java.awt.Color(165, 165, 165));
        pBloodType.setEditable(true);
        pBloodType.setForeground(new java.awt.Color(0, 0, 0));
        pBloodType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        pBloodType.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        pBloodType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pBloodTypeActionPerformed(evt);
            }
        });
        jPanel1.add(pBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 70, 20));

        pCivilStatus.setBackground(new java.awt.Color(165, 165, 165));
        pCivilStatus.setForeground(new java.awt.Color(0, 0, 0));
        pCivilStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "Single", "Married", "Divorced/Seraparated", "Widowed", "In a Civil Partnership (Live in Partner)" }));
        pCivilStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        pCivilStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pCivilStatusActionPerformed(evt);
            }
        });
        jPanel1.add(pCivilStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 120, 20));

        doc.setBackground(new java.awt.Color(165, 165, 165));
        doc.setForeground(new java.awt.Color(0, 0, 0));
        doc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Doctor Selected" }));
        doc.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docActionPerformed(evt);
            }
        });
        jPanel1.add(doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 290, -1));

        jButton2.setBackground(new java.awt.Color(68, 114, 196));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 630, 60, 30));

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Clear");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 630, 70, 30));

        checkbox1.setLabel("Information are correct");
        checkbox1.setName("Information are correct"); // NOI18N
        checkbox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox1ItemStateChanged(evt);
            }
        });
        jPanel1.add(checkbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, -1, 20));

        Schedule.setForeground(new java.awt.Color(0, 0, 0));
        Schedule.setText("Schedule");
        jPanel1.add(Schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 370, -1));

        assistant.setForeground(new java.awt.Color(0, 0, 0));
        assistant.setText("Assistant");
        jPanel1.add(assistant, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 360, -1));

        contact.setForeground(new java.awt.Color(0, 0, 0));
        contact.setText("Contact");
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 360, -1));

        depart.setBackground(new java.awt.Color(165, 165, 165));
        depart.setForeground(new java.awt.Color(0, 0, 0));
        depart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO DEPARTMENT SELECTED", "GENERAL MEDICINE", "CARDIOLOGY", "NEUROLOGY", "PEDIATRICS", "ORTHOPEDICS", "DERMATOLOGY", "GYNECOLOGY", "UROLOGY", "NEPHROLOGY", "PULMONOLOGY", "ENDOCRINOLOGY", "PSYCHIATRY", "GASTROENTEROLOGY", "HEMATOLOGY", "ONCOLOGY", "RADIOLOGY", "ANESTHESIOLOGY", "OPHTHALMOLOGY", "OTOLARYNGOLOGY (ENT)", "DENTISTRY", "RHEUMATOLOGY", "GERIATRICS", "EMERGENCY MEDICINE", "PATHOLOGY", "PLASTIC SURGERY", "GENERAL SURGERY", "NEUROSURGERY", "OBSTETRICS", "SPORTS MEDICINE", "PALLIATIVE CARE" }));
        depart.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        depart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departActionPerformed(evt);
            }
        });
        jPanel1.add(depart, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 290, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Age error message");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, 20));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("Choose a department to filter doctors.");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 360, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("         You are Editing patient: ");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 57, 1360, 40));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setText("In case of Emergency");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 600, 30));

        jButton4.setBackground(new java.awt.Color(68, 114, 196));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 60, 30));

        jButton5.setText("Change Password");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    private void rNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        pBloodType.setSelectedItem(ONE.getText());
  
     find();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNameActionPerformed

    private void pSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pSexActionPerformed

    private void pBloodTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pBloodTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pBloodTypeActionPerformed

    private void pCivilStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pCivilStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pCivilStatusActionPerformed

    private void docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docActionPerformed
        // TODO add your handling code here:
       Schedule.setVisible(true);
       assistant.setVisible(true);
       contact.setVisible(true);

        try {
            File path2 = new File(fileLocDoctor + doc.getSelectedItem().toString() + ".txt");
                String paths = path2.toString();
                BufferedReader br = new BufferedReader(new FileReader(paths));
                String s;
                ArrayList<String> files = new ArrayList<>();

                while ((s = br.readLine()) != null) {
                    files.add(s.replaceAll(",", "|"));

                }

                String c = files.toString();
                String avail = c.split(",")[8].replace("|", ",");
                Schedule.setText(avail);

                String as = c.split(",")[11].replace("|", ",");
                assistant.setText(as);

                String con = c.split(",")[12];
                contact.setText(con);

            } catch (Exception e) {

            } 
    }//GEN-LAST:event_docActionPerformed

    private void checkbox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox1ItemStateChanged
        // TODO add your handling code here:
     
      afterSub();
    }//GEN-LAST:event_checkbox1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ifSubmit();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void departActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departActionPerformed
        // TODO add your handling code here:
        //Department Chosen
        dep();
    
    }//GEN-LAST:event_departActionPerformed

    private void pContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pContactActionPerformed

    private void pAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pAgeActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        mf.setResizable(false);
        mf.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ChangePass cp = new ChangePass();
        cp.setVisible(true);
        cp.setLocationRelativeTo(null);
        cp.setResizable(false);
        cp.cpPatientName.setText(patientName.getText());
        
    }//GEN-LAST:event_jButton5ActionPerformed
    public void find(){     
        try {
            
            File path2 = new File(fileLoc + "\\" + patientName.getText() + ".txt");
            String fileName = path2.toString();

            BufferedReader b = new BufferedReader(new FileReader(fileName));
            String s;

            ArrayList<String> files = new ArrayList<>();

            while ((s = b.readLine()) != null) {
                files.add(s.replace(",", "|"));
            }

            String c = files.toString();
            pName.setText(c.split(",")[1].replace("Name:", "").replaceFirst(" ", ""));
            pAge.setText(c.split(",")[2].replace("Age:", "").replaceFirst(" ", ""));
            pillness.setText(c.split(",")[3].replace("Illness:", "").replaceFirst(" ", ""));
            pAllergies.setText(c.split(",")[4].replace("|",",").replace("Allergies:", "").replaceFirst(" ", ""));
            pSex.setSelectedItem(c.split(",")[5].replace("Sex:", "").replaceFirst(" ", ""));
            pHeight.setText(c.split(",")[6].replace("Height:", "").replaceFirst(" ", "").replace("cm", "").replaceFirst(" ", ""));
            pBloodType.setSelectedItem(c.split(",")[7].replace("Blood Type:", "").replaceFirst(" ", ""));
            pWeight.setText(c.split(",")[8].replace("Weight:", "").replace("kg", "").replaceFirst(" ", ""));
            pAddress.setText(c.split(",")[9].replace("|", ",").replace("Address:", "").replaceFirst(" ", ""));
            pCivilStatus.setSelectedItem(c.split(",")[10].replace("Civil Status:", "").replaceFirst(" ", ""));
            
            String bday = c.split(",")[11].replace("Birthday:", "");
            month.setSelectedItem(bday.split(" ")[1]);
            day.setSelectedItem(bday.split(" ")[2]);
            year.setSelectedItem(bday.split(" ")[3]);
            
            pContact.setText(c.split(",")[12].replace("Contact Number:", "").replaceFirst(" ", ""));
            pEmail.setText(c.split(",")[13].replace("Email:", "").replaceFirst(" ", ""));
            rName.setText(c.split(",")[16].replace("Name:", "").replaceFirst(" ", ""));
            rContact.setText(c.split(",")[17].replace("Contact Number:", "").replaceFirst(" ", ""));
            relation.setText(c.split(",")[18].replace("Relation:", "").replaceFirst(" ", ""));
            rEmail.setText(c.split(",")[19].replace("Email:", "").replaceFirst(" ", ""));
            rAddress.setText(c.split(",")[20].replace("|",",").replace("Address:", "").replaceFirst(" ", ""));
            doc.getEditor().setItem(c.split(",")[21].replace("]", "").replace("Doctor:", "").replaceFirst(" ", ""));
            
            
            
            
        }catch(Exception e){
        
        
        }
    }
    
    public void clear(){
    //clear code
    
    year.setSelectedIndex(0);
    month.setSelectedIndex(0);
    day.setSelectedIndex(0);
    doc.setSelectedIndex(0);
    depart.setSelectedIndex(0);
    pBloodType.setSelectedIndex(0);
    pCivilStatus.setSelectedIndex(0);
    pSex.setSelectedIndex(0);
    pName.setText("");
    pAllergies.setText("");
    pAge.setText("");
    pillness.setText("");
    pWeight.setText("");
    pAddress.setText("");
    pHeight.setText("");
    pContact.setText("");
    relation.setText("");
    rContact.setText("");
    rName.setText("");
    rEmail.setText("");
    pEmail.setText("");
    checkbox1.setState(false);
    
    
    }
  
    public void afterSub(){
   
        if(a == true){
        
         int response = JOptionPane.showConfirmDialog(null, "         After clicking confirm, the information will be submitted. \n                                      Are you sure? ", "Confirm", JOptionPane.YES_NO_OPTION);

            if (response == JOptionPane.YES_OPTION) {
               jButton2.setEnabled(true);
            
            //dito lagay yung para di na maedit 
            
    year.setEnabled(false);
    month.setEnabled(false);
    day.setEnabled(false);
    doc.setEnabled(false);
    depart.setEnabled(false);
    pBloodType.setEnabled(false);
    pCivilStatus.setEnabled(false);
    pSex.setEnabled(false);
    pName.setEnabled(false);
    pAllergies.setEnabled(false);
    pAge.setEnabled(false);
    pillness.setEnabled(false);
    pWeight.setEnabled(false);
    pAddress.setEnabled(false);
    pHeight.setEnabled(false);
    pContact.setEnabled(false);
    relation.setEnabled(false);
    rContact.setEnabled(false);
    rName.setEnabled(false);
    rEmail.setEnabled(false);
    pEmail.setEnabled(false);
    checkbox1.setEnabled(false);
    pName.setEditable(false);
    pAllergies.setEditable(false);
    pAge.setEditable(false);
    pillness.setEditable(false);
    pWeight.setEditable(false);
    pAddress.setEditable(false);
    pHeight.setEditable(false);
    pContact.setEditable(false);
    relation.setEditable(false);
    rContact.setEditable(false);
    rName.setEditable(false);
    rEmail.setEditable(false);
    pEmail.setEditable(false);
            
            }else{
            
            
            }
        }
        
    } 
    
    public void ifSubmit(){
        //no no here dont
       String age = pAge.getText().toString();
        if (!age.isEmpty()) {
            try {

                jLabel2.setText("");
                int age1 = Integer.parseInt(age);

                if (age1 < 18) {
                    String m = "a minor";
                    setAge(m);
                }
                if (age1 >= 18 && age1 <= 60) {
                    String m = "an adult";
                setAge(m);
                }
                if (age1 >= 60) {
                    String m = "a Senior Citizen";
                  setAge(m);
                   a = true;
                }
            } catch (NumberFormatException e) {
               a = false; 
               jLabel2.setText("Incorrect Age");
                jLabel2.setForeground(Color.red);
                Path fileToDeletePath = Paths.get(patientName.getText() + ".txt");
                
                try {
                    Files.delete(fileToDeletePath);
                } catch (IOException ex) {
                }

            }
        }

        //Relative info
  
        try {

            File parentDir = new File(fileLoc);

            FileWriter writer = new FileWriter(fileLoc + "\\" + patientName.getText()+".txt");

           writer.write("-------------------Patient Information------------------");
            writer.write("\nName:" + pName.getText().replace("  ", " ").toUpperCase());
            writer.write("\nAge:" + age);
            writer.write("\nIllness:" + pillness.getText().toUpperCase());
            writer.write("\nAllergies:" + pAllergies.getText().replace(",", "|").toUpperCase());
            writer.write("\nSex:" + pSex.getSelectedItem().toString().toUpperCase());
            writer.write("\nHeight:" + pHeight.getText() + " cm");
            writer.write("\nBlood Type:" + pBloodType.getSelectedItem().toString());
            writer.write("\nWeight:" + pWeight.getText() + " kg");
            writer.write("\nAddress:" + pAddress.getText().toUpperCase().replace(",", "|"));
            writer.write("\nCivil Status:" + pCivilStatus.getSelectedItem().toString());
            writer.write("\nBirthday:" + month.getSelectedItem().toString() + " " + day.getSelectedItem().toString() + " " + year.getSelectedItem().toString());
            writer.write("\nContact Number:" + pContact.getText());
            writer.write("\nEmail:" + pEmail.getText().toUpperCase());
            writer.write("\nPatient is " + getAge());
            writer.write("\n-------------------Emergency Contact------------------");
            writer.write("\nName:" + rName.getText().toUpperCase());
            writer.write("\nContact Number:" + rContact.getText().toUpperCase());
            writer.write("\nRelation:" + relation.getText().toUpperCase());
            writer.write("\nEmail:" + rEmail.getText().toUpperCase());
            writer.write("\nAddress:" + rAddress.getText().toUpperCase());
            writer.write("\nDoctor:" + doc.getSelectedItem().toString());

            writer.close();

        } catch (Exception e) {

        }

        
    }
    
    public void allDoc(){
    
            File path = new File(fileLocDoctor);
        File[] files = path.listFiles();
        ArrayList<String> fileArray = new ArrayList<>();

        for (int i = 0; i < files.length;) {

            if (files[i].isFile()) {
                try {
                   
                    Arrays.sort(files);
                            int num = 0;
                            String n = files[i].getName().toString();
                            fileArray.add(n);
                            String aa = n.split(",")[num].replace(".txt", "");
                            doc.addItem(aa);
                            num++;
                            System.out.println(n);

                } catch (Exception e) {

                }
            }
            i++;
        }
        
    }
    
    /**
     * @param args the command line arguments
     */ 
    public void dep() {
        doc.removeAllItems();
        File path = new File(fileLocDoctor);
        File[] files = path.listFiles();
        ArrayList<String> fileArray = new ArrayList<>();

        for (int i = 0; i < files.length;) {

            if (files[i].isFile()) {
                try {
                    BufferedReader br = new BufferedReader(new FileReader(files[i]));
                    String s;
                    Arrays.sort(files);

                    while ((s = br.readLine()) != null) {
                        if (s.trim().contains(depart.getSelectedItem().toString())) {
                            int num = 0;
                            String n = files[i].getName().toString();
                            fileArray.add(n);
                            String aa = n.split(",")[num].replace(".txt", "");
                            doc.addItem(aa);
                            num++;
                            System.out.println(n);
                        }

                    }
                    br.close();

                } catch (Exception e) {

                }
            }
            i++;
        } if(depart.getSelectedItem().toString() == "NO DEPARTMENT SELECTED"){
          allDoc();
        }
    }
 
    public void setAge(String ageM){
        this.ageM = ageM;
    }
    public String getAge(){
        return ageM;
    
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Schedule;
    private javax.swing.JLabel assistant;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JLabel contact;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JComboBox<String> depart;
    private javax.swing.JComboBox<String> doc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField pAddress;
    private javax.swing.JTextField pAge;
    private javax.swing.JTextField pAllergies;
    private javax.swing.JComboBox<String> pBloodType;
    private javax.swing.JComboBox<String> pCivilStatus;
    private javax.swing.JTextField pContact;
    private javax.swing.JTextField pEmail;
    private javax.swing.JTextField pHeight;
    private javax.swing.JTextField pName;
    private javax.swing.JComboBox<String> pSex;
    private javax.swing.JTextField pWeight;
    public javax.swing.JLabel patientName;
    private javax.swing.JTextField pillness;
    private javax.swing.JTextField rAddress;
    private javax.swing.JTextField rContact;
    private javax.swing.JTextField rEmail;
    private javax.swing.JTextField rName;
    private javax.swing.JTextField relation;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
