package com.mycompany.finalstp;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Arrays;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author nicol
 */
public class MainFrame extends javax.swing.JFrame  {

//MAINFRAME
    /**
     * Creates new form Doctor
     */
    String pass;
    String passLoc = "C:\\Users\\nicol\\Desktop\\Database\\Password.txt";

    public MainFrame() {

        initComponents();
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        error.setVisible(false);
        jLabel4.setVisible(false);
        jTextField1.setVisible(false);
        error1.setVisible(false);
        jButton2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        error1 = new javax.swing.JLabel();
        showPass2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        showPass = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        error = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        button5 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 100, 100));
        setMaximizedBounds(null);
        setMinimumSize(new java.awt.Dimension(1092, 702));
        setSize(new java.awt.Dimension(1092, 702));

        jDesktopPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(1092, 702));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1092, 500));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(1092, 702));
        jPanel1.setPreferredSize(new java.awt.Dimension(1092, 702));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordField2.setBackground(new java.awt.Color(102, 102, 102));
        jPasswordField2.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyTyped(evt);
            }
        });
        jPanel3.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 150, -1));

        jToggleButton2.setBackground(new java.awt.Color(153, 204, 255));
        jToggleButton2.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButton2.setText("👁️");
        jToggleButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton2StateChanged(evt);
            }
        });
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 80, -1, 26));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("To change admin password, access required.");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 290, 20));

        jTextField1.setBackground(new java.awt.Color(102, 102, 102));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 150, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Input new Password: ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 130, -1));

        jButton2.setBackground(new java.awt.Color(68, 114, 196));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 50, 20));

        error1.setForeground(new java.awt.Color(0, 0, 0));
        error1.setText("Password Error");
        jPanel3.add(error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 100, 20));

        showPass2.setForeground(new java.awt.Color(51, 51, 51));
        showPass2.setText(" ");
        jPanel3.add(showPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 100, 20));

        jButton3.setBackground(new java.awt.Color(68, 114, 196));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cancel");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 450, 250));

        jLabel1.setBackground(new java.awt.Color(14, 21, 20));
        jLabel1.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(14, 21, 20));
        jLabel1.setText("How may we help you today?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 269, 553, 56));

        button2.setBackground(new java.awt.Color(117, 194, 248));
        button2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button2.setLabel("New Patient");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 152, 58));
        button2.getAccessibleContext().setAccessibleParent(this);

        button3.setActionCommand("button2");
        button3.setBackground(new java.awt.Color(117, 194, 248));
        button3.setLabel("New Doctor");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 152, 58));

        button4.setActionCommand("button3");
        button4.setBackground(new java.awt.Color(117, 194, 248));
        button4.setLabel("Find Patient");
        button4.setName(""); // NOI18N
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        jPanel1.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 152, 58));

        jLabel2.setBackground(new java.awt.Color(14, 21, 20));
        jLabel2.setFont(new java.awt.Font("Sitka Small", 0, 44)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(14, 21, 20));
        jLabel2.setText("Welcome to RUMNICELS Medical Center! ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 207, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 120, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Admin access required.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 140, 20));

        showPass.setForeground(new java.awt.Color(102, 102, 102));
        showPass.setText(" ");
        jPanel2.add(showPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 120, 30));

        jToggleButton1.setBackground(new java.awt.Color(153, 204, 255));
        jToggleButton1.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButton1.setText("👁️");
        jToggleButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton1StateChanged(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, 26));

        error.setForeground(new java.awt.Color(0, 0, 0));
        error.setText("Password Error");
        jPanel2.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 360, 110));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText(" ⚙ Settings");
        jButton1.setBorder(null);
        jButton1.setIconTextGap(1);
        jButton1.setMaximumSize(new java.awt.Dimension(20, 20));
        jButton1.setMinimumSize(new java.awt.Dimension(20, 20));
        jButton1.setPreferredSize(new java.awt.Dimension(20, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, 70, 25));

        button5.setActionCommand("button3");
        button5.setBackground(new java.awt.Color(117, 194, 248));
        button5.setLabel("Find Doctor");
        button5.setName(""); // NOI18N
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        jPanel1.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 152, 58));

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jDesktopPane1.getAccessibleContext().setAccessibleParent(jDesktopPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        //find patienbt
        FindPatient b1 = new FindPatient();
        b1.setVisible(true);
        b1.setLocationRelativeTo(null);
        this.dispose();
        b1.setResizable(false);

    }//GEN-LAST:event_button4ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        checkPass();
        //new doctor
        jPanel2.setVisible(true);

    }//GEN-LAST:event_button3ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        //new patient

        NewPatient b2 = new NewPatient();
        b2.setVisible(true);
        b2.setLocationRelativeTo(null);
        this.dispose();
        b2.setResizable(false);
    }//GEN-LAST:event_button2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jToggleButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1StateChanged

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:

        if (jToggleButton1.isSelected()) {
            String pass = Arrays.toString(jPasswordField1.getPassword());
            System.out.println(pass);
            showPass.setText(pass.toString().replace(",", "").replace("]", "").replace("[", "").replace(" ", ""));
        }

        if (!jToggleButton1.isSelected()) {
            showPass.setText("");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        // TODO add your handling code here:
        error.setVisible(false);
        if (jToggleButton1.isSelected()) {
            String pass = Arrays.toString(jPasswordField1.getPassword());
            System.out.println(pass);
            showPass.setText(pass.toString().replace(",", "").replace("]", "").replace("[", "").replace(" ", ""));
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                if (getPass().equals(pass.toString().replace(",", "").replace("]", "").replace("[", "").replace(" ", ""))) {
                    NewDoctor nd = new NewDoctor();
                    nd.setVisible(true);
                    nd.setResizable(false);
                    nd.setLocationRelativeTo(null);
                    this.dispose();
                } else {
                    error.setForeground(Color.red);
                    error.setVisible(true);

                }
            }
        }

        if (!jToggleButton1.isSelected()) {
            String pass = Arrays.toString(jPasswordField1.getPassword());
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                if (getPass().equals(pass.toString().replace(",", "").replace("]", "").replace("[", "").replace(" ", ""))) {
                    NewDoctor nd = new NewDoctor();
                    nd.setVisible(true);
                    nd.setResizable(false);
                    nd.setLocationRelativeTo(null);
                    this.dispose();

                } else {

                    error.setForeground(Color.red);
                    error.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        checkPass();
        jPanel3.setVisible(true);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2KeyPressed

    private void jPasswordField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyReleased
        // TODO add your handling code here:

        if (jToggleButton2.isSelected()) {
            checkPass();
            String pass = Arrays.toString(jPasswordField2.getPassword());
            System.out.println(pass);
            showPass2.setText(pass.toString().replace(",", "").replace("]", "").replace("[", "").replace(" ", ""));
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                if (getPass().equals(pass.toString().replace(",", "").replace("]", "").replace("[", "").replace(" ", ""))) {
                    jLabel4.setVisible(true);
                    jTextField1.setVisible(true);
                    jButton2.setEnabled(true);
                } else {
                    error1.setForeground(Color.red);
                    error1.setVisible(true);

                }

            }
        }

        if (!jToggleButton2.isSelected()) {
            checkPass();
            String pass = Arrays.toString(jPasswordField2.getPassword());
            System.out.println(pass);
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                if (getPass().equals(pass.toString().replace(",", "").replace("]", "").replace("[", "").replace(" ", ""))) {
                    File path = new File(passLoc);
                    try {
                        jLabel4.setVisible(true);
                        jTextField1.setVisible(true);
                        jButton2.setEnabled(true);
                    } catch (Exception e) {

                    }
                } else {
                    error1.setForeground(Color.red);
                    error1.setVisible(true);

                }

            }

        }
    }//GEN-LAST:event_jPasswordField2KeyReleased

    private void jPasswordField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2KeyTyped

    private void jToggleButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2StateChanged

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:

        if (jToggleButton2.isSelected()) {
            String pass = Arrays.toString(jPasswordField2.getPassword());
            System.out.println(pass);
            showPass2.setText(pass.toString().replace(",", "").replace("]", "").replace("[", "").replace(" ", ""));
        }
        if (!jToggleButton2.isSelected()) {
            showPass2.setText("");
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        File path = new File(passLoc);
        try {
            FileWriter writer = new FileWriter(passLoc);
            writer.write(jTextField1.getText().toString());
            writer.close();

        } catch (Exception e) {

        }
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        FindDoctor fd = new FindDoctor();
        fd.setVisible(true);
        fd.setResizable(false);
        fd.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_button5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void checkPass() {
        File path = new File(passLoc);

        try {

            BufferedReader buff = new BufferedReader(new FileReader(path));
            String s = buff.readLine().toString();
            setPass(s);
            System.out.println(s);
            buff.close();

        } catch (Exception e) {

        }
    }

    public void setPass(String pass) {
        this.pass = pass;
    }

    public String getPass() {
        return pass;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame dr = new MainFrame();
                dr.setLocationRelativeTo(null);
                dr.setVisible(true);
                dr.setResizable(false);

                //dr.setExtendedState(dr.MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private javax.swing.JLabel error;
    private javax.swing.JLabel error1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel showPass;
    private javax.swing.JLabel showPass2;
    // End of variables declaration//GEN-END:variables
}
