package com.mycompany.finalstp;


import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nicol
 */
public class NewPatient extends javax.swing.JFrame {
    String fileName;
    String docN;
boolean error = false;
// new patient
    String m; //PatientAge
    String fileLoc = "C:\\Users\\nicol\\Desktop\\Database\\Patient";
    
    public NewPatient() {
        initComponents();
        jButton2.setEnabled(false);
        jButton4.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar2 = new java.awt.MenuBar();
        menu4 = new java.awt.Menu();
        menu5 = new java.awt.Menu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        namelabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        namelabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        namelabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        namelabel3 = new javax.swing.JLabel();
        namelabel4 = new javax.swing.JLabel();
        namelabel5 = new javax.swing.JLabel();
        namelabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        namelabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        namelabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        namelabel9 = new javax.swing.JLabel();
        namelabel10 = new javax.swing.JLabel();
        namelabel11 = new javax.swing.JLabel();
        namelabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        namelabel13 = new javax.swing.JLabel();
        namelabel14 = new javax.swing.JLabel();
        namelabel15 = new javax.swing.JLabel();
        namelabel16 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        namelabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        namelabel19 = new javax.swing.JLabel();

        menu4.setLabel("File");
        menu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu4ActionPerformed(evt);
            }
        });
        menuBar2.add(menu4);

        menu5.setLabel("Edit");
        menuBar2.add(menu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Management");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1092, 702));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("New Patient");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(68, 114, 196));
        jButton1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(12, 46, 4));
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        jButton1.setMaximumSize(new java.awt.Dimension(42, 20));
        jButton1.setMinimumSize(new java.awt.Dimension(42, 20));
        jButton1.setPreferredSize(new java.awt.Dimension(42, 19));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 30));

        namelabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel.setForeground(new java.awt.Color(0, 0, 0));
        namelabel.setText("Address: ");
        jPanel1.add(namelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, -1, 30));

        jButton2.setBackground(new java.awt.Color(68, 114, 196));
        jButton2.setForeground(new java.awt.Color(1, 13, 2));
        jButton2.setText("Done");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 500, 70, 30));

        jTextField1.setBackground(new java.awt.Color(165, 165, 165));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 153), null));
        jTextField1.setMinimumSize(new java.awt.Dimension(64, 24));
        jTextField1.setPreferredSize(new java.awt.Dimension(64, 24));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 200, 24));
        jTextField1.getAccessibleContext().setAccessibleName("FirstName");
        jTextField1.getAccessibleContext().setAccessibleParent(jTextField1);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Age:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, 50));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Illness / Concern:  ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, 30));

        jTextField4.setBackground(new java.awt.Color(165, 165, 165));
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 153), null));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 200, 24));
        jTextField4.getAccessibleContext().setAccessibleName("LastName");

        namelabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel1.setForeground(new java.awt.Color(0, 0, 0));
        namelabel1.setText("Last Name:");
        jPanel1.add(namelabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 65, -1));

        jTextField2.setBackground(new java.awt.Color(165, 165, 165));
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 153), null));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 60, 20));
        jTextField2.getAccessibleContext().setAccessibleName("age");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("    Ready to Choose a doctor? Please ensure that the above information have been filled.");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 1080, 40));

        namelabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel2.setForeground(new java.awt.Color(0, 0, 0));
        namelabel2.setText("Civil Status:");
        jPanel1.add(namelabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(165, 165, 165));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "Female", "Male", "Everyday" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 102), null));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 106, -1));
        jComboBox1.getAccessibleContext().setAccessibleName("Sex");

        namelabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel3.setForeground(new java.awt.Color(0, 0, 0));
        namelabel3.setText("Sex: ");
        jPanel1.add(namelabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, 30));

        namelabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel4.setForeground(new java.awt.Color(0, 0, 0));
        namelabel4.setText("kg.");
        jPanel1.add(namelabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, 30));

        namelabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel5.setForeground(new java.awt.Color(0, 0, 0));
        namelabel5.setText("Birthdate: ");
        jPanel1.add(namelabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, -1, 50));

        namelabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel6.setForeground(new java.awt.Color(0, 0, 0));
        namelabel6.setText("cm.");
        jPanel1.add(namelabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 40, 30));

        jComboBox2.setBackground(new java.awt.Color(165, 165, 165));
        jComboBox2.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "Single", "Married", "Divorced/Seraparated", "Widowed", "In a Civil Partnership (Live in Partner)" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, -1, 26));
        jComboBox2.getAccessibleContext().setAccessibleName("CiStatus");

        jComboBox3.setBackground(new java.awt.Color(165, 165, 165));
        jComboBox3.setEditable(true);
        jComboBox3.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901", "1900" }));
        jComboBox3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, -1, -1));
        jComboBox3.getAccessibleContext().setAccessibleName("BdYear");

        jComboBox4.setBackground(new java.awt.Color(165, 165, 165));
        jComboBox4.setEditable(true);
        jComboBox4.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBox4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 80, -1));
        jComboBox4.getAccessibleContext().setAccessibleName("BdMonth");

        jComboBox5.setBackground(new java.awt.Color(165, 165, 165));
        jComboBox5.setEditable(true);
        jComboBox5.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 60, -1));
        jComboBox5.getAccessibleContext().setAccessibleName("BdDay");

        jTextField5.setBackground(new java.awt.Color(165, 165, 165));
        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        jTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 110, 24));
        jTextField5.getAccessibleContext().setAccessibleName("Weight");

        jTextField6.setBackground(new java.awt.Color(165, 165, 165));
        jTextField6.setForeground(new java.awt.Color(0, 0, 0));
        jTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 110, 24));
        jTextField6.getAccessibleContext().setAccessibleName("Height");

        jTextPane1.setBackground(new java.awt.Color(153, 153, 153));
        jTextPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jTextPane1.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTextPane1);
        jTextPane1.getAccessibleContext().setAccessibleName("Textillness");

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 420, 60));

        namelabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel7.setForeground(new java.awt.Color(0, 0, 0));
        namelabel7.setText("Address: ");
        jPanel1.add(namelabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, 50));

        jTextField7.setBackground(new java.awt.Color(165, 165, 165));
        jTextField7.setForeground(new java.awt.Color(0, 0, 0));
        jTextField7.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 420, 24));
        jTextField7.getAccessibleContext().setAccessibleName("conAddress");

        namelabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel8.setForeground(new java.awt.Color(0, 0, 0));
        namelabel8.setText("Email: ");
        jPanel1.add(namelabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, -1, 50));

        jTextField8.setBackground(new java.awt.Color(165, 165, 165));
        jTextField8.setForeground(new java.awt.Color(0, 0, 0));
        jTextField8.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 800, 24));
        jTextField8.getAccessibleContext().setAccessibleName("Address");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("  Hospital Admission: Enter Patient's Information");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1080, 37));

        namelabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel9.setForeground(new java.awt.Color(0, 0, 0));
        namelabel9.setText("First Name:");
        jPanel1.add(namelabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        namelabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel10.setForeground(new java.awt.Color(0, 0, 0));
        namelabel10.setText("Name: ");
        jPanel1.add(namelabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, 30));

        namelabel11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel11.setForeground(new java.awt.Color(0, 0, 0));
        namelabel11.setText("Please Confirm/Submit the neccessary information first.");
        jPanel1.add(namelabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 130, 30));

        namelabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel12.setForeground(new java.awt.Color(0, 0, 0));
        namelabel12.setText("Relationship with the Patient: ");
        jPanel1.add(namelabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 210, 30));

        jTextField9.setBackground(new java.awt.Color(165, 165, 165));
        jTextField9.setForeground(new java.awt.Color(0, 0, 0));
        jTextField9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 260, 24));
        jTextField9.getAccessibleContext().setAccessibleName("Email");

        jTextField10.setBackground(new java.awt.Color(165, 165, 165));
        jTextField10.setForeground(new java.awt.Color(0, 0, 0));
        jTextField10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 260, 24));
        jTextField10.getAccessibleContext().setAccessibleName("conName");

        jTextField11.setBackground(new java.awt.Color(165, 165, 165));
        jTextField11.setForeground(new java.awt.Color(0, 0, 0));
        jTextField11.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 260, 24));
        jTextField11.getAccessibleContext().setAccessibleName("conContact");

        jTextField12.setBackground(new java.awt.Color(165, 165, 165));
        jTextField12.setForeground(new java.awt.Color(0, 0, 0));
        jTextField12.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 300, 24));
        jTextField12.getAccessibleContext().setAccessibleName("Rela");

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Clear");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 630, 70, 30));

        namelabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel13.setForeground(new java.awt.Color(0, 0, 0));
        namelabel13.setText("Height: ");
        jPanel1.add(namelabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, 50));

        namelabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel14.setForeground(new java.awt.Color(0, 0, 0));
        namelabel14.setText("cm.");
        jPanel1.add(namelabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 40, 30));

        namelabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel15.setForeground(new java.awt.Color(0, 0, 0));
        namelabel15.setText("Weight: ");
        jPanel1.add(namelabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, 30));

        namelabel16.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel16.setForeground(new java.awt.Color(0, 0, 0));
        namelabel16.setText("Contact no. :");
        jPanel1.add(namelabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, -1, 50));

        jTextField13.setBackground(new java.awt.Color(165, 165, 165));
        jTextField13.setForeground(new java.awt.Color(0, 0, 0));
        jTextField13.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 260, 24));
        jTextField13.getAccessibleContext().setAccessibleName("contactNum");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("  In Case Of Emergency Please Contact: ");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 1080, 37));

        jToggleButton1.setBackground(new java.awt.Color(68, 114, 196));
        jToggleButton1.setText("Confirm");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 630, -1, -1));

        namelabel17.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel17.setForeground(new java.awt.Color(0, 0, 0));
        namelabel17.setText("Email: ");
        jPanel1.add(namelabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, -1, 30));

        jButton4.setBackground(new java.awt.Color(68, 114, 196));
        jButton4.setText("Choose Doctor");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 150, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("  ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 110, -1));

        jTextField14.setBackground(new java.awt.Color(165, 165, 165));
        jTextField14.setForeground(new java.awt.Color(0, 0, 0));
        jTextField14.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 260, 24));

        namelabel19.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        namelabel19.setForeground(new java.awt.Color(0, 0, 0));
        namelabel19.setText("Contact No. :");
        jPanel1.add(namelabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 702));
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
     
       
        
     sub sub = new sub();
       sub.setVisible(true);
       sub.setLocationRelativeTo(null);
       sub.setResizable(false);
       this.dispose();
       
 /*            
     Timer timer = new Timer(3000, new ActionListener(){
    public void actionPerformed(ActionEvent evt) {
     
        sub.dispose();
    MainFrame dr = new MainFrame();
    dr.setVisible(true);

}
});

       timer.setRepeats(false);
       timer.start();*/
 
 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainFrame dr = new MainFrame();
        dr.setVisible(true);
        dr.pack();
        dr.setLocationRelativeTo(null);
        dr.setResizable(false);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void menu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
//  JOptionPane.showMessageDialog(null, "Note that after clicking yes, you will not be able to edit the set information. \n Continue?", "Confirm Submmision: ", JOptionPane.WARNING_MESSAGE);
    ifSubmit();
if(error == false){
    int  response = JOptionPane.showConfirmDialog(null,"         After clicking confirm, the information will be submitted. \n                                      Are you sure? ", "Confirm",JOptionPane.YES_NO_OPTION);
        
        if ( response == JOptionPane.YES_OPTION){  
            
            ifSubmit();
            jToggleButton1.setEnabled(false);
            jButton2.setEnabled(true);
            jButton4.setEnabled(true);
            
            jTextField1.setEditable(false);
            jTextField1.setFocusable(false);
            
            jTextField2.setEditable(false);
            jTextField2.setFocusable(false);
            
            jTextField4.setEditable(false);
           jTextField4. setFocusable(false);
            
           jTextPane1.setEditable(false);
           jTextPane1.setFocusable(false);
           
          jComboBox1.setEditable(false);
          jComboBox1.setEnabled(false);
           
            jTextField6.setEditable(false);
           jTextField6.setFocusable(false);
           
            jTextField5.setEditable(false);
           jTextField5.setFocusable(false);
           
            jTextField8.setEditable(false);
           jTextField8.setFocusable(false);
           
            jComboBox2.setEditable(false);
           jComboBox2.setEnabled(false);
           
            jComboBox4.setEditable(false);
           jComboBox4.setEnabled(false);
           
           jComboBox3 .setEditable(false);
           jComboBox3.setEnabled(false);
           
           jComboBox5 .setEditable(false);
           jComboBox5.setEnabled(false);
           
            jTextField13.setEditable(false);
          jTextField13.setFocusable(false);
           
           jTextField9.setEditable(false);
          jTextField9.setFocusable(false);
           
            jTextField10.setEditable(false);
           jTextField10.setFocusable(false);
           
            jTextField11.setEditable(false);
           jTextField11.setFocusable(false);
           
            jTextField12.setEditable(false);
           jTextField12.setFocusable(false);
           
            jTextField7.setEditable(false);
            jTextField7.setFocusable(false);
           
        }else{
        jButton4.setEnabled(false);
        jButton2.setEnabled(false);
        } }else{
        jButton4.setEnabled(false);
        jButton2.setEnabled(false);}
}
        

    
    
    public void ifSubmit(){      
        
             String FirstName = jTextField1.getText();
        String LastName = jTextField4.getText();
        String age = jTextField2.getText();
        String illness = jTextPane1.getText();
        String  Sex = jComboBox1.getSelectedItem().toString();
        String Height = jTextField6.getText();
        String Weight = jTextField5.getText();
        String address = jTextField8.getText();
        String civilStat = jComboBox2.getSelectedItem().toString();
        String month = jComboBox4.getSelectedItem().toString();
        String year = jComboBox3.getSelectedItem().toString();
        String day= jComboBox5.getSelectedItem().toString();
        String ContactNo = jTextField13.getText();
        String email = jTextField9.getText();
        
        if(!age.isEmpty()){ 
            
            try{
            error = false;
            jLabel7.setText("");
        int age1 = Integer.parseInt(age);
         
         if (age1 < 18){
             String m = "Patient is minor";
                setPatientAge(m);
         } if (age1 >= 18 && age1 <= 60){
             String m = "Patient is an adult";
                setPatientAge(m);
         } if (age1 >= 60){
             String m = "Patient is a Senior Citizen";
             setPatientAge(m);
         }
                        }catch(NumberFormatException e){
                            error = true;
                            jLabel7.setText("Incorrect Age");
                            jLabel7.setForeground(Color.red);
                            Path fileToDeletePath = Paths.get(getFileName());
                                        try {
                                        Files.delete(fileToDeletePath);
                                        } catch (IOException ex) {
                                                }
            
                        }
        }   
        //Relative info
        String conName = jTextField10.getText();
        String conNum = jTextField11.getText();
        String rela = jTextField12.getText();
        String ConAddress = jTextField7.getText();
        String rEmail = jTextField11.getText();
        
        String FileName = LastName + FirstName+ ".txt";
        setFileName(FileName);
      
        try{
        File parentDir = new File (fileLoc);
        parentDir.mkdir();

        File file = new File (parentDir, FileName);
       file.createNewFile();
       
       
         FileWriter writer = new FileWriter(fileLoc +"\\" + FileName);
         
         writer.write("-------------------Patient Information------------------");
         writer.write("\nName: " + FirstName + " " + LastName);
         writer.write("\nAge: " + age);
         writer.write("\nIllness: " + illness);
         writer.write("\nSex: " + Sex);
         writer.write("\nHeight: "+Height);
         writer.write("\nWeight: "+Weight);
         writer.write("\nAddress: "+address);
         writer.write("\nCivil Status: "+civilStat);
         writer.write("\nBirthday: " +month + " " +day + " "+year);
         writer.write("\nContact Number: " + ContactNo);
         writer.write("\nEmail: " + email);
         writer.write("\n-------------------Emergency Contact------------------");
         writer.write("\nName: " +conName);
         writer.write("\nContact Number: " + conNum);
         writer.write("\nRelationship with the Patient: " + rela);
         writer.write("\nAddress: "+ConAddress);
         writer.write("\nDoctor: " + getDoctorName());
         writer.write("\nEmail: " + rEmail);
         writer.write("\n" + getPatientAge());
       
      
         writer.close();
        }catch(Exception e){
        
        }
        
 
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Clear
        jTextField1.setText("");
        jTextField4.setText("");
        jTextField2.setText("");
        jTextPane1.setText("");
        jComboBox1.setSelectedIndex(0);
        jTextField6.setText("");
        jTextField5.setText("");
        jTextField8.setText("");
        jComboBox2.setSelectedIndex(0);
}
    
    
    public void setFileName(String fileName){
    
    this.fileName = fileName;
    
    } 
    public String getFileName(){

        return fileName;

 }
    public void setPatientAge(String m){
        
        
        this.m = m;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        NewDoctor nd = new NewDoctor();
        nd.setVisible(true);
        nd.setLocationRelativeTo(null);
        nd.setResizable(false);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed
    
     public String getPatientAge(){
         return m;
     
     }
     
     public void setDoctorName(String docN){
         this.docN = docN;
}
     public String getDoctorName(){
     
         return docN;
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPatient().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.MenuBar menuBar2;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel namelabel1;
    private javax.swing.JLabel namelabel10;
    private javax.swing.JLabel namelabel11;
    private javax.swing.JLabel namelabel12;
    private javax.swing.JLabel namelabel13;
    private javax.swing.JLabel namelabel14;
    private javax.swing.JLabel namelabel15;
    private javax.swing.JLabel namelabel16;
    private javax.swing.JLabel namelabel17;
    private javax.swing.JLabel namelabel19;
    private javax.swing.JLabel namelabel2;
    private javax.swing.JLabel namelabel3;
    private javax.swing.JLabel namelabel4;
    private javax.swing.JLabel namelabel5;
    private javax.swing.JLabel namelabel6;
    private javax.swing.JLabel namelabel7;
    private javax.swing.JLabel namelabel8;
    private javax.swing.JLabel namelabel9;
    // End of variables declaration//GEN-END:variables
}
