/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalstp;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author nicol
 */
public class Password extends javax.swing.JFrame {

    /**
     * Creates new form Password
     */
    String Ppass;
    String Apass;
    String pName;
    int frame;
    String adminPassLoc = "C:\\Users\\nicol\\Desktop\\Database\\Password.txt";
    String patientPassLoc = "C:\\Users\\nicol\\Desktop\\Database\\Patient\\";

    public Password() {
        initComponents();
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        butSP1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("                                 Password Required. Enter password for patient");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 490, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Patient Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 210, 30));

        jPasswordField1.setBackground(new java.awt.Color(165, 165, 165));
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 130, 30));

        butSP1.setBackground(new java.awt.Color(255, 255, 255));
        butSP1.setForeground(new java.awt.Color(0, 0, 0));
        butSP1.setText("👁️");
        butSP1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                butSP1StateChanged(evt);
            }
        });
        butSP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSP1ActionPerformed(evt);
            }
        });
        jPanel1.add(butSP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 50, 30));

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("show password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 100, 20));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("error message");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 250, -1));

        jButton1.setBackground(new java.awt.Color(68, 114, 196));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 50, 20));

        jButton2.setBackground(new java.awt.Color(68, 114, 196));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butSP1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_butSP1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_butSP1StateChanged

    private void butSP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSP1ActionPerformed
        // TODO add your handling code here:
        String pass = Arrays.toString(jPasswordField1.getPassword());
        if (butSP1.isSelected()) {
            jLabel2.setVisible(true);
            jLabel2.setText(pass.toString().replace(",", "").replace("]", "").replace("[", "").replace(" ", ""));

        } else {
            jLabel2.setText("");
        }
    }//GEN-LAST:event_butSP1ActionPerformed

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        // TODO add your handling code here:
        jLabel3.setVisible(false);
        try {
            String pass = Arrays.toString(jPasswordField1.getPassword());
            if (butSP1.isSelected()) {
                jLabel2.setVisible(true);
                jLabel2.setText(pass.toString().replace(",", "").replace("]", "").replace("[", "").replace(" ", ""));
            } else {
                jLabel2.setText("");
            }
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                PatientPass();
                System.out.println(getPpass());
                AdminPass();
                System.out.println(getApass());

                String enterPass = pass.toString().replace(",", "").replace("]", "").replace("[", "").replace(" ", "");
                System.out.println(enterPass);
                if (enterPass.matches(getApass()) || enterPass.matches(getPpass())) {
                    new FindPatient().dispose();
                    PatientPass();
                    AdminPass();
                    sCase();

                } else {
                    errorMessages();
                }
            } else {

            }
        } catch (Exception e) {
            errorMessages();
        }

    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PatientPass();
        System.out.println(getPpass());
        AdminPass();
        System.out.println(getApass());
        String pass = Arrays.toString(jPasswordField1.getPassword());
        String enterPass = pass.toString().replace(",", "").replace("]", "").replace("[", "").replace(" ", "");
        System.out.println(enterPass);
        if (enterPass.matches(getApass()) || enterPass.matches(getPpass())) {
            PatientPass();
            AdminPass();
            sCase();

        } else {
            errorMessages();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
       
           FindPatient fp = new FindPatient();
        fp.setVisible(true);
        fp.setResizable(false);
        fp.setLocationRelativeTo(null);
        fp.jComboBox2.getEditor().setItem(jLabel1.getText());
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void errorMessages() {

        int rnd = (int) (Math.random() * 4);

        ArrayList<String> ar = new ArrayList<>();
        ar.add("Password is incorrect. Please try again.");
        ar.add("Access denied: Wrong password provided.");
        ar.add("Login unsuccessful: Password incorrect.");
        ar.add("Error: Password mismatch.");

        String error = ar.toString().split(",")[rnd].replace("[", "").replace("]", "");
        jLabel3.setForeground(Color.red);
        jLabel3.setText(error);
        jLabel3.setVisible(true);

    }

    public void PatientPass() {
        try {

            File path = new File(patientPassLoc + jLabel1.getText().toString() + ".txt");
            String fileName = path.toString();

            BufferedReader b = new BufferedReader(new FileReader(fileName));
            String s;

            ArrayList<String> files = new ArrayList<>();

            while ((s = b.readLine()) != null) {
                files.add(s.replace(",", "|").replace("[", ""));
            }
            System.out.println(s);
            b.close();
            String c = files.toString();

            String patientPW = c.split(",")[22].replace("Password:", "").replace(" ", "").replace("]", "");
            setPpass(patientPW);

        } catch (Exception e) {

        }

    }

    public void setPpass(String Ppass) {
        this.Ppass = Ppass;
    }

    public String getPpass() {
        return Ppass;
    }

    public void AdminPass() {

        File path = new File(adminPassLoc);

        try {

            BufferedReader buff = new BufferedReader(new FileReader(path));
            String s = buff.readLine().toString();
            setApass(s);
            System.out.println(s);
            buff.close();

        } catch (Exception e) {

        }
    }

    public void sCase() {

        switch (getFrame()) {
            case 1:

                PatientFile pf = new PatientFile();
                pf.setVisible(true);
                pf.setLocationRelativeTo(null);
                pf.setResizable(false);
                pf.jLabel1.setText(jLabel1.getText());
                this.dispose();
                
                break;
            case 2:
                newRecord nr = new newRecord();
                nr.setVisible(true);
                nr.setResizable(false);
                nr.setLocationRelativeTo(null);
                nr.namelabel1.setText(jLabel1.getText());
                this.dispose();
                 
                break;

            case 3:
                EditPatient ep = new EditPatient();
                ep.setVisible(true);
                ep.setResizable(false);
                ep.setLocationRelativeTo(null);
                ep.patientName.setText(jLabel1.getText());
                this.dispose();
                
                break;

        }

    }

    public void setApass(String Apass) {
        this.Apass = Apass;
    }

    public String getApass() {
        return Apass;
    }

    public void setFrame(int frame) {
        this.frame = frame;

    }

    public int getFrame() {
        return frame;
    }

    public void setName(String pName) {
        this.pName = pName;

    }

    public String getName() {
        return pName;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton butSP1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
